URL=https://raw.githubusercontent.com/wurli/jet/refs/heads/main/crates/lua/meta/jet.lua
STUBS=$(curl -sSL $URL)

OUT_FILE=./lua/jet/core/stubs.lua

echo "-- This file is auto-generated by scripts/import-types.sh
-- Do not edit this file directly. Instead, edit the source file at
-- $URL,
-- then run scripts/import-stubs.sh to regenerate this file.
" > $OUT_FILE

echo "$STUBS" >> $OUT_FILE

echo "Wrote type stubs to $OUT_FILE"
